id: IFA24FFAE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T06:48:58+00:00'
last_modified: '2022-06-08T01:29:19.758954+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5210
  title: དུས་རབས་ཀྱི་ལམ་སྟོན་གཞོན་ནུའི་མདུན་ལྗོངས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    45C8:
      image_group_id: I3CN5212
      title: ''
      total_pages: 307
      order: 1
      base_file: 45C8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
