id: IFA24FFAE
legacy_id: P004495
ocr_import_info:
  bdrc_scan_id: W3CN5210
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T06:47:08'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T14:53:47.476703+00:00'
last_modified: 2022-09-03 22:53:56.701130
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN5210
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW3CN5210
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དུས་རབས་ཀྱི་ལམ་སྟོན་གཞོན་ནུའི་མདུན་ལྗོངས།
  author: བློ་བཟང་མཁས་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.8926511334923092
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I3CN5212:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN5212
      total_pages: 307
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN5212.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8926511334923092
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
